import Vue from 'vue';

//手动导入安装VueRouter
import VueRouter from 'vue-router';
Vue.use(VueRouter)

//导入vuex
import Vuex from 'vuex';
Vue.use(Vuex);

//导入图片预览插件
import VuePreview from 'vue-preview';
Vue.use(VuePreview);
Vue.use(VuePreview, {
    mainClass: 'pswp--minimal--dark',
    barsSize: {top: 0, bottom: 0},
    captionEl: false,
    fullscreenEl: false,
    shareEl: false,
    bgOpacity: 0.85,
    tapToClose: true,
    tapToToggleControls: false
})

var store = new Vuex.Store({
    state:{
        companyInfoList: [
            {
                "enterpriseID": 1,
                "enterpriseName": "重庆红牛餐厅",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "洪山区广八路20号",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "李子琳",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256"
            },
            {
                "enterpriseID": 2,
                "enterpriseName": "武汉亢龙太子",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "东湖路店",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "王先源",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256"
            },
            {
                "enterpriseID": 3,
                "enterpriseName": "和心布艺",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "武昌区友谊大道友谊国际家居广场",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "张绍欣",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256"
            },
            {
                "enterpriseID": 4,
                "enterpriseName": "富山河装饰有限公司",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "	武昌区中南国际城B1座4A5楼",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "王富田",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256"
            },
            {
                "enterpriseID": 5,
                "enterpriseName": "骏浩图文广告公司",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "武昌区徐东大街中力名居",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "肖文睿",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256"
            },
            {
                "enterpriseID": 6,
                "enterpriseName": "龙元建设集团股份有限公司湖北分公司",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "	武昌区徐东大街福星惠誉写字楼8-1号27楼",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "刘思达",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256"
            },
            {
                "enterpriseID": 7,
                "enterpriseName": "湖北省中国旅行社有限责任公司",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "	武昌区中北路54号宏城金都A栋2401室",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "许巍",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256"
            },
        ],
        inspectionList:[
            {
                "enterpriseID": 1,
                "enterpriseName": "重庆红牛餐厅",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "洪山区广八路20号",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "李子琳",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256",
                "numberOfEnployees": "",
                "numberOfParttimeWorkers": "",
                "numberOfFulltimemployment": "",
                "numberOfParttimeLabor": "",
                "personnelNumberOfEthnicMinorities": "",
                "numberOfChildlabor": "",
                "hiteRetiredPeople": "",
                "employmentNumberIsRetreatedInside": "",
                "numberOfEmploymentAlreadyDealtWith": "",
                "disabledWorkersNumber": "",
                "foreignWorkers": "",
                "terminateThrLaborEmploymentRelationship": "",
                "laborDispatchUsingNumbers": "",
                "numberOffemaleWorker": "",
                "numberOfJuvenileWorkers": "",
                "numberOfMigrantWorkers": "",
                "unitToBorrowStaffNumbers": "",
                "internshipTraineePersonnel": "",
                "comparedToLastYearWorkerHas": "",
                "increaseOrDecreaseTheReason": "",
                "actualPayrollNumber": "",
                "totalActualPaymentOFWages": "",
                "individualMinimumWage": "",
                "ifWagesListProvided": "",
                "whetherOrWithholdWagesInArrears": "",
                "inViolantionOftheProvisionsOfTheMinimumWage": "",
                "anyViolationOfHighTemperatureAllowance": ""
            },
            {
                "enterpriseID": 2,
                "enterpriseName": "武汉亢龙太子",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "东湖路店",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "王先源",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256", 
                "numberOfEnployees": "",
                "numberOfParttimeWorkers": "",
                "numberOfFulltimemployment": "",
                "numberOfParttimeLabor": "",
                "personnelNumberOfEthnicMinorities": "",
                "numberOfChildlabor": "",
                "hiteRetiredPeople": "",
                "employmentNumberIsRetreatedInside": "",
                "numberOfEmploymentAlreadyDealtWith": "",
                "disabledWorkersNumber": "",
                "foreignWorkers": "",
                "terminateThrLaborEmploymentRelationship": "",
                "laborDispatchUsingNumbers": "",
                "numberOffemaleWorker": "",
                "numberOfJuvenileWorkers": "",
                "numberOfMigrantWorkers": "",
                "unitToBorrowStaffNumbers": "",
                "internshipTraineePersonnel": "",
                "comparedToLastYearWorkerHas": "",
                "increaseOrDecreaseTheReason": "",
                "actualPayrollNumber": "",
                "totalActualPaymentOFWages": "",
                "individualMinimumWage": "",
                "ifWagesListProvided": "",
                "whetherOrWithholdWagesInArrears": "",
                "inViolantionOftheProvisionsOfTheMinimumWage": "",
                "anyViolationOfHighTemperatureAllowance": ""

            },
            {
                "enterpriseID": 3,
                "enterpriseName": "和心布艺",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "武昌区友谊大道友谊国际家居广场",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "张绍欣",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256",
                "numberOfEnployees": "",
                "numberOfParttimeWorkers": "",
                "numberOfFulltimemployment": "",
                "numberOfParttimeLabor": "",
                "personnelNumberOfEthnicMinorities": "",
                "numberOfChildlabor": "",
                "hiteRetiredPeople": "",
                "employmentNumberIsRetreatedInside": "",
                "numberOfEmploymentAlreadyDealtWith": "",
                "disabledWorkersNumber": "",
                "foreignWorkers": "",
                "terminateThrLaborEmploymentRelationship": "",
                "laborDispatchUsingNumbers": "",
                "numberOffemaleWorker": "",
                "numberOfJuvenileWorkers": "",
                "numberOfMigrantWorkers": "",
                "unitToBorrowStaffNumbers": "",
                "internshipTraineePersonnel": "",
                "comparedToLastYearWorkerHas": "",
                "increaseOrDecreaseTheReason": "",
                "actualPayrollNumber": "",
                "totalActualPaymentOFWages": "",
                "individualMinimumWage": "",
                "ifWagesListProvided": "",
                "whetherOrWithholdWagesInArrears": "",
                "inViolantionOftheProvisionsOfTheMinimumWage": "",
                "anyViolationOfHighTemperatureAllowance": ""
            },
            {
                "enterpriseID": 4,
                "enterpriseName": "富山河装饰有限公司",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "	武昌区中南国际城B1座4A5楼",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "王富田",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256",
                "numberOfEnployees": "",
                "numberOfParttimeWorkers": "",
                "numberOfFulltimemployment": "",
                "numberOfParttimeLabor": "",
                "personnelNumberOfEthnicMinorities": "",
                "numberOfChildlabor": "",
                "hiteRetiredPeople": "",
                "employmentNumberIsRetreatedInside": "",
                "numberOfEmploymentAlreadyDealtWith": "",
                "disabledWorkersNumber": "",
                "foreignWorkers": "",
                "terminateThrLaborEmploymentRelationship": "",
                "laborDispatchUsingNumbers": "",
                "numberOffemaleWorker": "",
                "numberOfJuvenileWorkers": "",
                "numberOfMigrantWorkers": "",
                "unitToBorrowStaffNumbers": "",
                "internshipTraineePersonnel": "",
                "comparedToLastYearWorkerHas": "",
                "increaseOrDecreaseTheReason": "",
                "actualPayrollNumber": "",
                "totalActualPaymentOFWages": "",
                "individualMinimumWage": "",
                "ifWagesListProvided": "",
                "whetherOrWithholdWagesInArrears": "",
                "inViolantionOftheProvisionsOfTheMinimumWage": "",
                "anyViolationOfHighTemperatureAllowance": ""
            },
            {
                "enterpriseID": 5,
                "enterpriseName": "骏浩图文广告公司",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "武昌区徐东大街中力名居",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "肖文睿",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256",
                "numberOfEnployees": "",
                "numberOfParttimeWorkers": "",
                "numberOfFulltimemployment": "",
                "numberOfParttimeLabor": "",
                "personnelNumberOfEthnicMinorities": "",
                "numberOfChildlabor": "",
                "hiteRetiredPeople": "",
                "employmentNumberIsRetreatedInside": "",
                "numberOfEmploymentAlreadyDealtWith": "",
                "disabledWorkersNumber": "",
                "foreignWorkers": "",
                "terminateThrLaborEmploymentRelationship": "",
                "laborDispatchUsingNumbers": "",
                "numberOffemaleWorker": "",
                "numberOfJuvenileWorkers": "",
                "numberOfMigrantWorkers": "",
                "unitToBorrowStaffNumbers": "",
                "internshipTraineePersonnel": "",
                "comparedToLastYearWorkerHas": "",
                "increaseOrDecreaseTheReason": "",
                "actualPayrollNumber": "",
                "totalActualPaymentOFWages": "",
                "individualMinimumWage": "",
                "ifWagesListProvided": "",
                "whetherOrWithholdWagesInArrears": "",
                "inViolantionOftheProvisionsOfTheMinimumWage": "",
                "anyViolationOfHighTemperatureAllowance": ""
            },
            {
                "enterpriseID": 6,
                "enterpriseName": "龙元建设集团股份有限公司湖北分公司",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "	武昌区徐东大街福星惠誉写字楼8-1号27楼",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "刘思达",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256",
                "numberOfEnployees": "",
                "numberOfParttimeWorkers": "",
                "numberOfFulltimemployment": "",
                "numberOfParttimeLabor": "",
                "personnelNumberOfEthnicMinorities": "",
                "numberOfChildlabor": "",
                "hiteRetiredPeople": "",
                "employmentNumberIsRetreatedInside": "",
                "numberOfEmploymentAlreadyDealtWith": "",
                "disabledWorkersNumber": "",
                "foreignWorkers": "",
                "terminateThrLaborEmploymentRelationship": "",
                "laborDispatchUsingNumbers": "",
                "numberOffemaleWorker": "",
                "numberOfJuvenileWorkers": "",
                "numberOfMigrantWorkers": "",
                "unitToBorrowStaffNumbers": "",
                "internshipTraineePersonnel": "",
                "comparedToLastYearWorkerHas": "",
                "increaseOrDecreaseTheReason": "",
                "actualPayrollNumber": "",
                "totalActualPaymentOFWages": "",
                "individualMinimumWage": "",
                "ifWagesListProvided": "",
                "whetherOrWithholdWagesInArrears": "",
                "inViolantionOftheProvisionsOfTheMinimumWage": "",
                "anyViolationOfHighTemperatureAllowance": ""
            },
            {
                "enterpriseID": 7,
                "enterpriseName": "湖北省中国旅行社有限责任公司",
                "socialCreditCode": "91410104MA46UQPB3J",
                "enterpriseAddress": "	武昌区中北路54号宏城金都A栋2401室",
                "organizationCode": "MA018FG04",
                "managementStyle": "自营",
                "email": "2113@126.com",
                "website": "www.baidu.com",
                "industrialCategory": "餐饮",
                "fax": "testfax1",
                "establishDate": 1564416000000,
                "simpleName": "红牛",
                "enterpriseType": "餐厅",
                "economicType": "餐饮",
                "industryType": "餐饮",
                "moneyType": "人民币",
                "regisMoney": "20",
                "subordinateRelation": "test",
                "majorCharge": "食品局",
                "mainBusiness": "餐饮",
                "partBusiness": "餐饮",
                "businessNumber": "123",
                "legalRepresentative": "许巍",
                "repreTelephone": "13456784567",
                "repreID": "123",
                "enterpriseChargeName": "快本",
                "enterpriseChargeTelephone": "123466",
                "moneyChargeName": "里斯",
                "moneyChargeTelephone": "21456",
                "linkPerson": "里皮",
                "linkPersonTelephone": "21456",
                "handoutDate": 1564416000000,
                "effectiveDate": 1564416000000,
                "enterpriseAccountOpenBank": "124567",
                "accountOpenBank": "test1567",
                "bankAccount": "3256",
                "numberOfEnployees": "",
                "numberOfParttimeWorkers": "",
                "numberOfFulltimemployment": "",
                "numberOfParttimeLabor": "",
                "personnelNumberOfEthnicMinorities": "",
                "numberOfChildlabor": "",
                "hiteRetiredPeople": "",
                "employmentNumberIsRetreatedInside": "",
                "numberOfEmploymentAlreadyDealtWith": "",
                "disabledWorkersNumber": "",
                "foreignWorkers": "",
                "terminateThrLaborEmploymentRelationship": "",
                "laborDispatchUsingNumbers": "",
                "numberOffemaleWorker": "",
                "numberOfJuvenileWorkers": "",
                "numberOfMigrantWorkers": "",
                "unitToBorrowStaffNumbers": "",
                "internshipTraineePersonnel": "",
                "comparedToLastYearWorkerHas": "",
                "increaseOrDecreaseTheReason": "",
                "actualPayrollNumber": "",
                "totalActualPaymentOFWages": "",
                "individualMinimumWage": "",
                "ifWagesListProvided": "",
                "whetherOrWithholdWagesInArrears": "",
                "inViolantionOftheProvisionsOfTheMinimumWage": "",
                "anyViolationOfHighTemperatureAllowance": ""
            },
        ],
        caseList:[
            {
                caseTitle: "劳动保障监察处理流程",
                dateTime: "2018-11-30 10:28",
                caseContent: "武汉浩天电子股份有限公司",
                caseType: "调查取证",
                caseNumber: "武昌劳社监案字[2018]第4882号",
                lastPerson: "王娟",
                underTaker: "李伟",
                type: "1",
                enterpriceAddress: "",
                enterpriceNumber: "",
                chargePeople: "",
                lastPersonAdvice: "",
                chargePeoplePhone: "",
                casePersonNumber: "",
                caseMoney: ""
            },
            {
                caseTitle: "劳动保障监察处理流程",
                dateTime: "2018-10-19 09:49",
                caseContent: "美团司门口站点",
                caseType: "监察负责人审核",
                caseNumber: "武昌劳社监案字[2018]第4319号",                
                lastPerson: "王娟",
                underTaker: "李伟",
                type: "1",                
                enterpriceAddress: "",
                enterpriceNumber: "",
                chargePeople: "",
                lastPersonAdvice: "",
                chargePeoplePhone: "",
                casePersonNumber: "",
                caseMoney: ""
            },
            {
                caseTitle: "劳动保障监察处理流程",
                dateTime: "2018-10-12 14:40",
                caseContent: "文昱园林景观有限公司",
                caseType: "监察负责人审核",
                caseNumber: "武昌劳社监案字[2018]第4155号",                
                lastPerson: "王娟",
                underTaker: "李伟",
                type: "1",                
                enterpriceAddress: "",
                enterpriceNumber: "",
                chargePeople: "",
                lastPersonAdvice: "",
                chargePeoplePhone: "",
                casePersonNumber: "",
                caseMoney: ""
            },
            {
                caseTitle: "劳动保障监察处理流程",
                dateTime: "2018-10-11 10:24",
                caseContent: "武汉五洲建筑工程有限公司",
                caseType: "监察负责人审核",
                caseNumber: "武昌劳社监案字[2018]第4125号",                
                lastPerson: "王娟",
                underTaker: "李伟",
                type: "1",                
                enterpriceAddress: "",
                enterpriceNumber: "",
                chargePeople: "",
                lastPersonAdvice: "",
                chargePeoplePhone: "",
                casePersonNumber: "",
                caseMoney: ""
            },
            {
                caseTitle: "劳动保障监察处理流程",
                dateTime: "2018-10-11 10:24",
                caseContent: "贺胜桥鸡汤馆",
                caseType: "监察负责人审核",
                caseNumber: "武昌劳社监案字[2018]第4113号",                
                lastPerson: "王娟",
                underTaker: "李伟",
                type: "1",                
                enterpriceAddress: "",
                enterpriceNumber: "",
                chargePeople: "",
                lastPersonAdvice: "",
                chargePeoplePhone: "",
                casePersonNumber: "",
                caseMoney: ""

            },
            {
                caseTitle: "劳动保障监察处理流程",
                dateTime: "2018-07-31 10:49",
                caseContent: "武汉宾辰消防设备有限公司/武汉陇安泰防火材料公司(做工)",
                caseType: "监察负责人审核",
                caseNumber: "武昌劳社监案字[2018]第3398号",                
                lastPerson: "王娟",
                underTaker: "李伟",
                type: "2",                
                enterpriceAddress: "",
                enterpriceNumber: "",
                chargePeople: "",
                lastPersonAdvice: "",
                chargePeoplePhone: "",
                casePersonNumber: "",
                caseMoney: ""
            },
            {
                caseTitle: "劳动保障监察处理流程",
                dateTime: "2018-07-30 11:53",
                caseContent: "三医院（木工 昊宇公司）",
                caseType: "监察负责人审核",
                caseNumber: "武昌劳社监案字[2018]第3375号",                
                lastPerson: "王娟",
                underTaker: "李伟",
                type: "2",                                
                enterpriceAddress: "",
                enterpriceNumber: "",
                chargePeople: "",
                lastPersonAdvice: "",
                chargePeoplePhone: "",
                casePersonNumber: "",
                caseMoney: ""
            },
            {
                caseTitle: "劳动保障监察处理流程",
                dateTime: "2018-07-30 16:27",
                caseContent: "武昌公园",
                caseType: "监察负责人审核",
                caseNumber: "武昌劳社监案字[2018]第3380号",                
                lastPerson: "王娟",
                underTaker: "李伟",
                type: "2",                                
                enterpriceAddress: "",
                enterpriceNumber: "",
                chargePeople: "",
                lastPersonAdvice: "",
                chargePeoplePhone: "",
                casePersonNumber: "",
                caseMoney: ""
            },
        ]

    },
    mutations:{
        addCompanyInfo(state,companyInfo){
            state.companyInfoList.unshift(companyInfo);
        },
        addInspectionCompany(state,inspectionCompany){
            state.companyInfoList.unshift(inspectionCompany);
        },
        addCase(state,CaseInfo){
            state.caseList.unshift(CaseInfo);
        },
        deleteCase(state,CaseIndex){
            console.log('deletecase');
        }
    }
})


//导入 MUI 的样式
import './lib/mui/css/mui.min.css';
import './lib/mui/css/icons-extra.css';



import MintUI from 'mint-ui';
import 'mint-ui/lib/style.css';
Vue.use(MintUI);



//导入vue-resource
import VueResource from 'vue-resource'; 
//安装vue-resource
Vue.use(VueResource);

//全局设置post时候表单数据格式组织形式
Vue.http.options.emulateJSON = true;
Vue.http.options.root = 'http://172.16.10.84:8081/';
Vue.http.options.xhr = {
    withCredentials: true
}
//Vue.http.options.root = 'http://127.0.0.1:8081/';

// Vue.http.options.root = 'http://www.liulongbin.top:3005';

//导入APP根组件
import app from './APP.vue';

//导入格式化时间的插件
import moment from 'moment';

//导入自己的router.js路由模块
import router from './router.js';

//定义全局时间过滤器
Vue.filter('dateFormat',function(dataStr, pattern="YYYY-MM-DD HH:mm"){
    return moment(dataStr).format(pattern)
})

var vm = new Vue({
    el: '#app',
    render: c => c(app),
    router,
    store
})